version: '3'

services:
  service:
    build:
      context: .
    ports:
      - "8012:8012"

  postgres_service:  
    image: postgres:13.3  
    environment:  
      POSTGRES_DB: "db"  
      POSTGRES_USER: "admin"  
      POSTGRES_PASSWORD: "admin"
    ports:  
    - "5432:5432"