"""upgrade models

Revision ID: 5073597dc07b
Revises: 
Create Date: 2024-06-12 20:26:54.905427

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5073597dc07b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("FirstName", sa.String(), nullable=True),
        sa.Column("LastName", sa.String(), nullable=True),
        sa.Column("Email", sa.String(), nullable=True),
        sa.Column("Password", sa.String(), nullable=True),
        sa.Column("DateCreated", sa.DateTime(), nullable=True),
        sa.Column("DateLastVisited", sa.DateTime(), nullable=True),
        sa.Column("Active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("Email"),
    )
    op.create_table(
        "Tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("UserID", sa.Integer(), nullable=True),
        sa.Column("Token", sa.String(), nullable=True),
        sa.Column("RefreshToken", sa.String(), nullable=True),
        sa.Column("DateCreated", sa.DateTime(), nullable=True),
        sa.Column("DateUpdate", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["UserID"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Tokens")
    op.drop_table("Users")
    # ### end Alembic commands ###
